cart/urls.py
from django.urls import path

from . import views
from .views import cart_view

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

    path('', cart_view, name='cart_view'),

    path('update/', views.cart_update, name='cart_update'),

    path('delete/', views.cart_delete, name='cart_delete'),

    #path('count/', views.cart_count, name='cart_count'),


]

favorites/urls.py
from django.urls import path

from . import views

app_name = 'favorites'

urlpatterns = [
    path('toggle/<int:product_id>/', views.favorite_toggle, name='toggle'),
    path('', views.favorites_list, name='list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path

from . import views
from .decorators import check_recaptcha
from .views import ProfileUser, delete_user, CustomPasswordResetView, CustomPasswordResetConfirmView

app_name = 'users'
urlpatterns = [
    path('signup/', check_recaptcha(views.RegisterUser.as_view()), name='signup'),
    path('login/', check_recaptcha(views.LoginUser.as_view()), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('change-password/', check_recaptcha(views.UserPasswordChange.as_view()), name='change_password'),
    #path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/complete/', PasswordChangeDoneView.as_view(template_name="users/password_change_complete.html"), name='password_change_complete'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='users/password_reset_done'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    path('delete-user/', delete_user, name='delete_user'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static '/css/output.css' %}>
    <link href="{% static '/css/profile.css' %}" rel="stylesheet">
    <title>Shop Gio</title>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>

<body>

    {% include "navbar.html" %}

    {% block content %}
    {% endblock content %}
</body>

</html>

<script src="{% static '/js/cart.js' %}"></script>

templates/delete_user_completed.html
{% extends 'base.html' %}

{% block content %}
Пользователь удален!
    <strong><a href="{% url 'categories:index' %}">Вернуться в главное меню</a></strong>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="font-sans p-4 mx-auto lg:max-w-7xl md:max-w-4xl sm:max-w-full">
    <h2 class="text-4xl font-extrabold text-gray-800 mb-12">Товары</h2>

    <div class="flex gap-12"> <!-- Отступ между колонками -->
        <!-- Фильтрация слева -->
        <div class="w-1/4">
            <form method="GET" class="bg-white p-6 rounded-lg shadow-md">
                <h3 class="text-2xl font-semibold text-gray-800 mb-6">Фильтры</h3>
                <div class="space-y-4">
                    <div>
                        <label for="min_price" class="block text-sm font-medium text-gray-700">Мин. цена</label>
                        <input type="number" name="min_price" id="min_price"
                            class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="От"
                            value="{{ request.GET.min_price }}">
                    </div>
                    <div>
                        <label for="max_price" class="block text-sm font-medium text-gray-700">Макс. цена</label>
                        <input type="number" name="max_price" id="max_price"
                            class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="До"
                            value="{{ request.GET.max_price }}">
                        <label for="min_weight" class="block text-sm font-medium text-gray-700">Мин. вес</label>
                        <input type="number" step="0.01" name="min_weight" id="min_weight"
                            class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="От"
                            value="{{ request.GET.min_weight }}">
                    </div>
                    <div>
                        <label for="max_weight" class="block text-sm font-medium text-gray-700">Макс. вес</label>
                        <input type="number" step="0.01" name="max_weight" id="max_weight"
                            class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="До"
                            value="{{ request.GET.max_weight }}">
                    </div>

                    <div class="flex items-end">
                        <button type="submit" class="bg-blue-600 text-white p-2 rounded-md w-full mt-6">Применить
                            фильтры
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <!-- Продукты справа -->
        <div class="w-5/6"> <!-- Увеличено пространство для продуктов -->
            {% if items %}
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-8">
                {% for item in items %}
                <!-- Основные изменения здесь -->
                <div
                    class="bg-white rounded overflow-hidden shadow-md cursor-pointer hover:scale-[1.02] transition-all flex flex-col h-full">
                    <!-- Добавляем flex и h-full -->
                    <a href="{% url 'myapp:id_item' item.id %}" class="block flex-grow">
                        <!-- flex-grow для растягивания -->
                        <div class="w-full h-48 overflow-hidden"> <!-- Фиксированная высота изображения -->
                            <img src="{{ item.image_url }}" alt="{{ item.name }}"
                                class="w-full h-full object-cover object-center" />
                        </div>
                        <div class="p-4 text-center">
                            <h3 class="text-lg font-bold text-gray-800 line-clamp-2">{{ item.name }}</h3>
                        </div>
                    </a>
                    <div class="px-2 flex items-center mt-auto pb-2"> <!-- mt-auto для прижатия к низу -->
                        <h4 class="text-lg font-bold text-gray-800">{{ item.price }} ₽</h4>
                        <button
                            class="wishlist-button ml-auto p-2 rounded-full hover:bg-gray-200 focus:outline-none transition-transform active:scale-90"
                            data-product-id="{{ item.id }}">
                            <img class="wishlist-icon w-6 h-6 cursor-pointer"
                                src="{% if item.id in favorites_ids %}/static/images/redWishlist.svg{% else %}/static/images/wishlist.svg{% endif %}"
                                alt="Wishlist">
                        </button>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p class="text-gray-500 text-lg">Нет доступных товаров.</p>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'js/index.js' %}"></script>
{% endblock content %}

templates/navbar.html
{% load static %}
<nav class="bg-white shadow-md py-4 px-6">
    <div class="flex items-center justify-between max-w-6xl mx-auto ml-auto">
        <a href="{% url 'myapp:index' %}" class="flex items-center gap-2">
            <img src="{% static '/images/shop.svg' %}" alt="logo" class="h-8 w-8">
            <span class="text-xl font-bold text-gray-800">Shop Gio</span>
        </a>

        <!-- Кнопка меню для мобильных устройств -->
        <button class="md:hidden flex items-center text-gray-600 hover:text-gray-800 ml-auto" id="mobile-menu-button">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
        </button>

        <!-- Меню -->
        <div class="hidden md:flex items-center gap-6 ml-auto space-x-1">
            <a href="{% url 'myapp:index' %}" class="text-gray-600 hover:text-gray-800 font-medium">Главное меню</a>
            <a href="#" class="text-gray-600 hover:text-gray-800 font-medium">О нас</a>
            <a href="#" class="text-gray-600 hover:text-gray-800 font-medium">Контакты</a>
        </div>

        <!-- Правая часть -->
        <div class="hidden md:flex items-center gap-6 ml-auto">
            <a href="{% url 'favorites:list' %}" class="relative flex flex-col items-center cursor-pointer">
                <img src="/static/images/redWishlist.svg" alt="Wishlist" class="w-8 h-8">
                <span id="favorites-count" class="text-gray-600 text-xs mt-1">{{ favorites_count|default:0 }}</span>
            </a>

            <a href="{% url 'cart:cart_view' %}" class="relative flex flex-col items-center cursor-pointer"
                id="cart-button">
                <img src="/static/images/cart.svg" alt="Cart" class="w-8 h-8">
                <span id="cart-count" class="text-gray-600 text-xs mt-1">
                    {% if cart_count > 0 %}
                    {{ cart_count }}
                    {% else %}
                    0
                    {% endif %}
                </span>

            </a>

            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" class="text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded">
                Профиль
            </a>
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded">
                    Выйти
                </button>
            </form>
            {% else %}
            <a href="{% url 'users:login' %}"
                class="text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded">Войти</a>
            {% endif %}
        </div>
    </div>

    <!-- Мобильное меню -->
    <div class="hidden" id="mobile-menu">
        <div class="flex flex-col items-start gap-4 mt-4 ml-auto">
            <a href="{% url 'myapp:index' %}" class="text-gray-600 hover:text-gray-800 font-medium">Главное меню</a>
            <a href="#" class="text-gray-600 hover:text-gray-800 font-medium">О нас</a>
            <a href="#" class="text-gray-600 hover:text-gray-800 font-medium">Контакты</a>
            <div class="flex flex-col items-start gap-2 mt-4">
                {% if user.is_authenticated %}
                <p class="text-gray-600 hover:text-gray-800 font-medium">{{ user.username }}</p>
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded">
                        Выйти
                    </button>
                </form>
                {% else %}
                <a href="{% url 'users:login' %}"
                    class="text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded">Войти</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

templates/phone.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="min-h-screen">
    <div class="max-w-6xl mx-auto p-6">
        <!-- Основной контейнер товара -->
        <div class="flex flex-col-reverse md:flex-row bg-white shadow-lg overflow-hidden">

            <!-- Панель мини-фотографий (скрыта на мобильных устройствах) -->
            <div class="w-full md:w-1/4 p-4 space-y-4 flex flex-col items-center md:block">
                <div class="w-24 h-24 rounded-lg border border-gray-300 p-1 cursor-pointer">
                    <img src="{{ item.image_url }}" alt="Фото 1" class="w-full h-full object-cover rounded-lg"
                        onclick="changeMainImage('{{ item.image_url }}')">
                </div>
                <div class="w-24 h-24 rounded-lg border border-gray-300 p-1 cursor-pointer">
                    <img src="{{ item.image_url }}" alt="Фото 2" class="w-full h-full object-cover rounded-lg"
                        onclick="changeMainImage('{{ item.image_url }}')">
                </div>
                <div class="w-24 h-24 rounded-lg border border-gray-300 p-1 cursor-pointer">
                    <img src="{{ item.image_url }}" alt="Фото 3" class="w-full h-full object-cover rounded-lg"
                        onclick="changeMainImage('{{ item.image_url }}')">
                </div>
            </div>

            <!-- Основное фото товара -->
            <div
                class="w-full md:w-3/4 p-4 flex justify-center items-center bg-gray-100 border border-gray-300 rounded-lg">
                <img id="main-image" src="{{ item.image_url }}" alt="Основное фото"
                    class="w-full h-auto object-cover rounded-lg">
            </div>

            <!-- Информация о товаре -->
            <div class="w-full md:w-2/3 p-6 flex flex-col justify-between">
                <!-- id и название товара с вишлистом -->
                <div class="flex items-center justify-between">
                    <p class="text-gray-600">id: {{ item.id }}</p>
                    <button
                        class="wishlist-button hover:text-red-700 hover:bg-gray-200 focus:outline-none transition-transform active:scale-90 rounded-lg"
                        data-product-id="{{ item.id }}">
                        <img class="wishlist-icon w-6 h-6 cursor-pointer"
                            src="{% if is_favorite %}/static/images/redWishlist.svg{% else %}/static/images/wishlist.svg{% endif %}"
                            alt="Wishlist">
                    </button>
                </div>

                <!-- Название товара -->
                <h1 class="text-3xl font-semibold text-gray-900 mt-1">{{ item.name }}</h1>

                <div class="flex flex-col md:flex-row items-center justify-between my-auto mx-8">
                    <!-- Цена -->
                    <p class="text-3xl font-bold text-green-600">
                        {{ item.price }}₽
                    </p>

                    <!-- Кнопка купить -->
                    <button data-product-id="{{ item.id }}"
                        class="add-to-cart bg-blue-600 text-white hover:bg-blue-700 px-6 py-2 rounded-md mt-4 md:mt-0 w-3/5 transition-all transform hover:scale-105">
                        Купить
                    </button>
                </div>

                <!-- Характеристики товара (Тип и Вес) внизу -->
                <div class="space-y-2 mt-auto">
                    <div class="flex justify-between">
                        <span class="text-gray-600 font-medium">Тип:</span>
                        <span class="text-gray-800">{{ item.type }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-gray-600 font-medium">Категория:</span>
                        <span class="text-gray-800">{{ item.category.name }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-gray-600 font-medium">Вес:</span>
                        <span class="text-gray-800">{{ item.weight }} кг</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Описание товара -->
        <div class="mt-8 p-8 bg-white rounded-xl shadow-xl border-l-4 border-blue-500">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Описание товара</h2>
            <p class="text-gray-600 text-lg leading-relaxed">{{ item.description }}</p>
        </div>
    </div>
</div>

<!-- JS для смены основного фото -->
<script>
    function changeMainImage(newImageUrl) {
        document.getElementById("main-image").src = newImageUrl;
    }
</script>

<script src="{% static 'js/index.js' %}"></script>

{% endblock content %}