cart/urls.py
from django.urls import path

from . import views
from .views import cart_view

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

    path('', cart_view, name='cart_view'),

    path('update/', views.cart_update, name='cart_update'),

    path('delete/', views.cart_delete, name='cart_delete'),

    #path('count/', views.cart_count, name='cart_count'),


]

orders/urls.py
from django.urls import path

from . import views



app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/<int:order_id>/', views.order_created, name='order_created'),
    path('info/', views.order_info, name='order_info'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path

from . import views
from .decorators import check_recaptcha
from .views import ProfileUser, delete_user, CustomPasswordResetView, CustomPasswordResetConfirmView

app_name = 'users'
urlpatterns = [
    path('signup/', check_recaptcha(views.RegisterUser.as_view()), name='signup'),
    path('login/', check_recaptcha(views.LoginUser.as_view()), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('change-password/', check_recaptcha(views.UserPasswordChange.as_view()), name='change_password'),
    #path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/complete/', PasswordChangeDoneView.as_view(template_name="users/password_change_complete.html"), name='password_change_complete'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='users/password_reset_done'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    path('delete-user/', delete_user, name='delete_user'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to='media/%Y/%m/%d/', blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")
    email = models.EmailField(null=True, blank=True, unique=True)

users/forms.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django import forms
from django.contrib.auth.forms import PasswordResetForm


class NewUserForm(UserCreationForm):
    username = forms.CharField(required=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(required=True, label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(required=True, label='Повторите пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }
        error_messages = {
            'email': {
                'unique': "Такой E-mail уже существует!",
            },
        }

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин/E-mail',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        this_year = datetime.date.today().year
        self.fields['date_birth'] = forms.DateField(
            label='Дата рождения',
            widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5)))
        )

    class Meta:
        model = get_user_model()
        fields = ['photo', 'first_name', 'last_name', 'username', 'email', 'date_birth']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'E-mail',
            'username': 'Логин',
            'date_birth': 'Дата рождения',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'username': forms.TextInput(attrs={'class': 'form-input'}),
        }


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="E-mail",
        widget=forms.EmailInput(attrs={'class': 'form-input'}),
    )

class CustomPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from djangoProject import settings
from .forms import NewUserForm, LoginUserForm, UserPasswordChangeForm, ProfileUserForm, CustomPasswordResetConfirmForm
from .forms import CustomPasswordResetForm
from django.contrib.auth.views import PasswordResetView, \
    PasswordResetConfirmView


class RegisterUser(CreateView):
    """Handles user registration."""
    form_class = NewUserForm
    template_name = 'users/signup.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if self.request.recaptcha_is_valid:
            form.save()
            return super().form_valid(form)

        return render(self.request, 'users/signup.html', self.get_context_data())


class LoginUser(LoginView):
    """Handles user login."""
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Вход'}

    def post(self, request, *args, **kwargs):
        if not request.recaptcha_is_valid:
            return self.form_invalid(self.get_form())
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """Called after successful login - sync session cart to DB"""
        response = super().form_valid(form)
        
        # Sync session cart to database cart
        from cart.CartBase import CartSyncService
        CartSyncService.sync_session_to_db(self.request)
        
        # Sync session favorites to database favorites
        from favorites.FavoritesBase import FavoriteSyncService
        FavoriteSyncService.sync_session_to_db(self.request)
        
        return response

    def get_success_url(self):
        return reverse('myapp:index')


class ProfileUser(LoginRequiredMixin, UpdateView):
    """Handles user profile updates."""
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': 'Профиль пользователя',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_tab'] = 'profile'
        context['edit_mode'] = self.request.GET.get('edit', 'false') == 'true'
        return context


class UserPasswordChange(LoginRequiredMixin, PasswordChangeView):
    """Handles user password change."""
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_complete')
    template_name = "users/password_change.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_tab'] = 'change_password'
        return context

    def post(self, request, *args, **kwargs):
        if not request.recaptcha_is_valid:
            return self.form_invalid(self.get_form())
        return super().post(request, *args, **kwargs)


def delete_user(request):
    """Handles user deletion."""
    if request.method == 'POST':
        user = request.user
        user.delete()

        return redirect('users:delete_user')

    return render(request, 'delete_user_completed.html')


class CustomPasswordResetView(PasswordResetView):
    """Handles user password reset functionality."""
    form_class = CustomPasswordResetForm
    template_name = "users/password_reset_form.html"
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:users/password_reset_done")


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    """Handles user password reset confirmation."""
    form_class = CustomPasswordResetConfirmForm
    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="flex items-center justify-center min-h-screen">
        <div class="bg-white p-6 rounded-lg shadow-md w-full md:w-1/4">
            <h2 class="text-2xl font-semibold text-center text-gray-800 mb-4">Вход в аккаунт</h2>

            <form method="post" class="space-y-4">
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                    <p><label class="form-label text-sm font-medium text-gray-700"
                              for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <p>
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="form-group g-recaptcha" data-sitekey="6LfjY78qAAAAAOR1KC8wdL2Qud_0UDza9XQZBAPF"></div>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
                    <button type="submit"
                            class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition duration-200">
                        Войти
                    </button>
                </p>
            </form>
            <hr>
            {% include 'users/social.html' %}
            <div class="mt-1 text-center text-sm text-gray-600">
                <a href="{% url 'users:password_reset' %}" class="text-blue-500 hover:underline">Забыли пароль?</a>
            </div>
            <div class="text-center text-sm text-gray-600">
                <span>Все еще нет аккаунта? </span>
                <a href="{% url 'users:signup' %}" class="text-blue-500 hover:underline">Зарегистрироваться</a>
            </div>
        </div>
    </div>



{% endblock %}

templates/users/password_change.html
{% extends 'users/profile_navigate.html' %}

{% block main_content %}
    <div class="w-full">
        <h2 class="text-2xl font-semibold mb-4 text-center">Сменить пароль</h2>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <div class="flex items-center mb-4">
                    <label class="form-label w-32 text-right pr-4" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                    <div class="flex-1">
                        {{ f }}
                    </div>
                </div>
                <div class="form-error text-center mb-4">{{ f.errors }}</div>
            {% endfor %}
        <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="form-group g-recaptcha" data-sitekey="6LfjY78qAAAAAOR1KC8wdL2Qud_0UDza9XQZBAPF"></div>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
            <div class="text-center">
                <button type="submit" class="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700">
                    Изменить пароль
                </button>
            </div>
        </form>
    </div>
{% endblock %}

templates/users/password_change_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a class="text-blue-600 font-bold" href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
 
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>Новый пароль</h1>
    <form method="post">
        {% csrf_token %}
        <div class="for-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
    <p><button type="submit">Сохранить</button></p>
    </form>
{% endblock %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h1>Сброс пароля</h1>
    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="flex justify-center items-center min-h-screen bg-gray-100">
        <div class="bg-white p-8 rounded-lg shadow-lg w-full max-w-xs">
            <h1 class="text-2xl font-semibold text-center text-gray-800 mb-6">Восстановление пароля</h1>
            <form method="post" class="space-y-4">
                {% csrf_token %}
                {% for f in form %}
                    <div class="form-group">
                        <label for="{{ f.id_for_label }}" class="block text-sm font-medium text-gray-700">{{ f.label }}</label>
                        <div class="mt-1">
                            {{ f }}
                        </div>
                        <div class="text-red-500 text-sm mt-1">
                            {% for error in f.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="flex justify-center mt-4">
                    <button type="submit" class="w-full py-2 px-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
                        Сбросить по E-mail
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'users/profile_navigate.html' %}

{% block main_content %}
    <div class="w-full max-w-3xl mx-auto">
        <h2 class="text-2xl font-semibold mb-4 text-center">Профиль пользователя</h2>

        {% if not edit_mode %}
            <div class="space-y-6">
                <div class="flex justify-center mb-6">
                    {% if user.photo %}
                        <div class="w-40 h-40 overflow-hidden rounded-full border border-gray-300 shadow">
                            <img src="{{ user.photo.url }}" alt="photo" class="object-cover w-full h-full">
                        </div>
                    {% else %}
                        <div class="w-40 h-40 overflow-hidden rounded-full border border-gray-300 shadow">
                            <img src="{{ default_image }}" alt="photo" class="object-cover w-full h-full">
                        </div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <strong>Имя:</strong> {{ user.first_name }}
                </div>
                <div class="mb-4">
                    <strong>Фамилия:</strong> {{ user.last_name }}
                </div>
                <div class="mb-4">
                    <strong>Логин:</strong> {{ user.username }}
                </div>
            
                <div class="mb-4">
                    <strong>Email:</strong> {{ user.email }}
                </div>
                <div class="mb-4">
                    <strong>Дата регистрации:</strong> {{ user.date_joined|date:"d.m.Y" }}
                </div>
                <div class="mb-4">
                    <strong>Дата рождения:</strong> {{ user.date_birth|date:"d.m.Y" }}
                </div>

                <div class="text-center">
                    <a href="?edit=true"
                       class="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition">
                        Редактировать
                    </a>
                </div>
            </div>
        {% else %}
            <form method="post" class="space-y-6" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="flex justify-center mb-6">
                    {% if user.photo %}
                        <div class="w-40 h-40 overflow-hidden rounded-full border border-gray-300 shadow">
                            <img src="{{ user.photo.url }}" alt="photo" class="object-cover w-full h-full">
                        </div>
                    {% else %}
                        <div class="w-40 h-40 overflow-hidden rounded-full border border-gray-300 shadow">
                            <img src="{{ default_image }}" alt="photo" class="object-cover w-full h-full">
                        </div>
                    {% endif %}
                </div>

                <div class="form-error text-center text-red-500">{{ form.non_field_errors }}</div>

                {% for f in form %}
                    <div class="flex items-center mb-4">
                        <label class="form-label w-32 text-right pr-4"
                               for="{{ f.id_for_label }}">{{ f.label }}: </label>
                        <div class="flex-1">
                            {{ f }}
                        </div>
                    </div>
                    <div class="form-error text-center text-red-500 mb-4">{{ f.errors }}</div>
                {% endfor %}

                <div class="text-center">
                    <button type="submit"
                            class="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition">
                        Сохранить
                    </button>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/users/profile_navigate.html
{% extends 'base.html' %}

{% block content %}
    <div class="min-h-screen flex justify-center items-center py-16">
        <div class="flex w-full max-w-6xl bg-slate-200 p-6 rounded-lg shadow-md">
            <div class="w-1/4 p-6 rounded-lg shadow-md">
                <ul class="space-y-4">
                    <li>
                        <a href="{% url 'users:profile' %}" class="block text-blue-500 hover:text-blue-700">
                            Профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'orders:order_info' %}" class="block text-blue-500 hover:text-blue-700">
                            Мои заказы
                        </a>
                    </li>
                    {% if not users.has_usable_password %}
                        <li>
                            <a href="{% url 'users:change_password' %}" class="block text-blue-500 hover:text-blue-700">
                                Сменить пароль
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <form method="post" action="{% url 'users:delete_user' %}">
                            {% csrf_token %}
                            <button type="submit" class="block text-red-500 hover:text-red-700">
                                Удалить аккаунт
                            </button>
                        </form>
                    </li>
                </ul>
            </div>

            <div class="w-full ml-4">
                {% block main_content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
        <div class="bg-white p-6 rounded-lg shadow-md w-full md:w-1/4 ">
            <h2 class="text-2xl font-semibold text-center text-gray-800 mb-4">Регистрация</h2>
            <form action="{% url 'users:signup' %}" method="post" class="space-y-4">
                {% csrf_token %}

                <div class="flex flex-col">
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        <p><label class="form-label text-sm font-medium text-gray-700"
                                  for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                </div>
                <p>
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="form-group g-recaptcha" data-sitekey="6LfjY78qAAAAAOR1KC8wdL2Qud_0UDza9XQZBAPF"></div>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
                <button type="submit"
                        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition duration-200">
                    Зарегистрироваться
                </button>
                </p>
            </form>
            {% include 'users/social.html' %}
            <!-- Ссылки для восстановления пароля и входа -->
            <div class="mt-4 text-center text-sm text-gray-600">
                <a href="#" class="text-blue-500 hover:underline">Забыли пароль?</a>
            </div>
            <div class="text-center text-sm text-gray-600">
                <span>Все еще нет аккаунта?</span>
                <a href="{% url 'users:login' %}" class="text-blue-500 hover:underline">Войти</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/social.html
{% block social %}
    <p class="text-gray-600 text-center">или</p>
    <p class="flex justify-center"><a href="{% url 'social:begin' 'github' %}"><img
            src="/static/images/social/github.png" alt="github" class="mt-1 w-11 h-auto"></a>
        <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="/static/images/social/gmail.png" alt="gmail"
                                                                class="mt-1 w-11 h-auto"></a></p>
{% endblock %}